#!/bin/sh /etc/rc.common
START=50                

start() {
   /usr/sbin/dnscrypt-proxy --daemonize --local-address='127.0.0.1:5353' --user=nobody --resolvers-list='/usr/share/dnscrypt-proxy/dnscrypt-resolvers.csv' --resolver-name='dnscrypt.eu-dk'
}                                                 
 
stop() {
   killall 'dnscrypt-proxy'
}
